### ISSUE TITLE
Minor Update needed for user guide document

### ISSUE THREAD

**Issue by DMillerAK** [USDA-NRCS/HEL-Tools#32]
I noticed in both the table of contents on lesson 3 and also on page 7 title in the user guide document. - it refers to WC tool not the HEL tool.  Also on page 7 the Download the WC tool should be HELC tool.  I know these are quick and easy updates but wanted to share for correction.

**Comment by dylan-harwell-usda** [comment]
Hey @DMillerAK Thanks for the report here. This was brought to my attention in an email. Chris is handling the guides, I will pass this along to him when he returns from leave.

**Comment by DMillerAK** [comment]
Thanks! I didn't see it listed as an issue but wanted the info relayed.

**Comment by dylan-harwell-usda** [comment]
User Guide updated and pushed.
