### ISSUE TITLE
County list in A.01 not current for Alaska

### ISSUE THREAD

**Issue by DMillerAK** [USDA-NRCS/HEL-Tools#33]
I noticed the Alaska list of counties is not current.  Had county issues with HEL/Wetland tools so I know there is a look up table to fix.  Is the correct place to update the counties the tool references the SUPPORT.gdb/lut_census_fips table?   We had 2 census areas (Copper River and Chugach) replace a single named census area (Valdez-Cordova) recently.

**Comment by dylan-harwell-usda** [comment]
I will have to defer this to Chris Morse, as I am not sure the intended process for keeping the table current, but you are correct, the dropdown list is built by the table in SUPPORT.gdb.

**Comment by DMillerAK** [comment]
I'll test in a different area and wait to hear back about updating the table. Thanks!

**Comment by dylan-harwell-usda** [comment]
For your local testing, I think it would be fine for you to make the update in the table.

**Comment by dylan-harwell-usda** [comment]
Added updated census lut to SUPPORT.gdb
