### ISSUE TITLE
Create Form, Letter, Report Error

### ISSUE THREAD

**Issue by JWN-NRCS** [USDA-NRCS/HEL-Tools#34]
I was running the Create Form, Letter, Report tool and got the following error:
![image](https://github.com/USDA-NRCS/HEL-Tools/assets/125605480/660df411-902b-4503-9ede-5d8f86209dda)

Running Pro 3.1.3

I had another user testing and she was having the same error as well on a different county.
Any help/suggestion to resolve this issue would be great.  
Thanks

**Comment by dylan-harwell-usda** [comment]
Hi @JWN-NRCS for starters, can you verify a folder path for me? Wherever you downloaded this tool package, you should have a folder called 'python_packages'. Do you have that folder and the 4 folders inside?
![image](https://github.com/USDA-NRCS/HEL-Tools/assets/120053864/f7afbd39-b7b4-463c-bac2-6aa6df8829ee)

**Comment by JWN-NRCS** [comment]
I did not.  I extracted from the .zip into my downloads folder then copied the resulting HEL folder to my C:\GIS_Tools folder.  For some reason, only the babel folder copied.  The tool worked now.
