### ISSUE TITLE
Edit Site_Prepare_HELC layer

### ISSUE THREAD

**Issue by jessegray2** [USDA-NRCS/HEL-Tools#35]
Is there a way for the HEL Determination to reflect edits to the Site_Prepare_HELC layer polygon? Producers may ask for a determination on parts of a field or the field may be split from a wetland determination not reflected in the CLU Map Service layer. After editing the Site_Prepare_HELC layer (splitting the polygon) and running the HEL Determination, I am not getting an accurate HEL determination on the split fields. The HEL determination is still being made on the entire field.
jesse.gray2@usda.gov

**Comment by dylan-harwell-usda** [comment]
Deferring to Chris Morse to answer as this is a policy-related question.

**Comment by CEM-NRCS** [comment]
Per Jason Outlaw, NRCS national policy lead on this issue:

_The tool is designed to operate on existing or planned CLU boundaries as provided by FSA according to their policy. NRCS is not authorized to make modifications to the CLU and thus must conduct the determination on the boundaries as provided by FSA. To potentially address the need for planned fields, see FSA Handbook 6-CP Part 357B regarding FSA creating new field breakings in the CLU before submitting and AD-1026 to NRCS._

https://emso-sa.fsa.usda.gov/dps/services/downloadhandler.ashx?fileid=41013

As a result, we should not modify the CLU and Site_Prepare_HELC layers' field boundaries in this workflow. Closing this issue.

**Comment by jessegray2** [comment]
Thank you for checking on this, Chris. I'll pass along to the HEL/WL team here.
