### ISSUE TITLE
CPA-026 typo / map prepared by NRCS comment

### ISSUE THREAD

**Issue by ksduncan** [USDA-NRCS/HEL-Tools#36]
A small typo in the 026 form that the tool generates in the remarks under part 9, ‘no’ should be ‘not’
"If a field is not listed, no determination was made at this time.  Contact the Farm Service Agency for previously determined HEL status of fields **_NOT_** listed below." 

Also, we noticed that there is no notation on the map product that it was made by NRCS. I have updated our local template to include the same terminology as located on CD exports where it says Prepared with assistance from USDA-Natural Resources Conservation Service. Just something that may want to be placed on the national template.

**Comment by dylan-harwell-usda** [comment]
Hi @ksduncan, thanks for the report. I will make the typo fix. Deferring to @CEM-NRCS for any additional language changes in the map layout.

**Comment by dylan-harwell-usda** [comment]
Typo has been fixed in 026 form.

**Comment by CEM-NRCS** [comment]
Referred the map question to Travis and Crystal. Map content policy in title 170 is being reviewed and needs to be updated. Until then, feel free to add the desired statement to your local version of the tool, but we will wait to modify the national release of the tool any further until those policies are updated.
