### ISSUE TITLE
Prepare Site DEM no values

### ISSUE THREAD

**Issue by jessegray2** [USDA-NRCS/HEL-Tools#38]
[ga015_t0013559_2024_01_log.txt](https://github.com/USDA-NRCS/HEL-Tools/files/14040778/ga015_t0013559_2024_01_log.txt)
[ga213_t0000994_2024_01_log.txt](https://github.com/USDA-NRCS/HEL-Tools/files/14040893/ga213_t0000994_2024_01_log.txt)

When running the Prepare Site DEM step of the tool with a Local Image, the Site_DEM created sometimes has no values though other times it creates a working Site_DEM. It seems to vary by different County datasets for the state though the datasets are 
in the same projection, same cell size, same elevation units. Of the two logs attached, tract 13559 did not produce a usable Site_DEM while tract 994 did.

**Comment by dylan-harwell-usda** [comment]
Issue still uncertain, but possibly due to using Mosaic dataset as local DEM input. Tested using out of the box GP tools 'Clip' and 'Extract by Mask', both producing bad resulting DEMs. Values appeared correct, but rendering on screen was bad. Further testing required.

**Comment by dylan-harwell-usda** [comment]
After some troubleshooting, we don't believe this is an issue with the tool, but with the input Mosaic Dataset. Closing issue.
