### ISSUE TITLE
026 Report, sodbuster default value

### ISSUE THREAD

**Issue by gregb-nrcs** [USDA-NRCS/HEL-Tools#41]
Can the default sodbuster value in the 026 report table column be changed to "blank" instead of "no"?  It seems easy to overlook that column when determination reports are generated.  It would be better and less error-prone if we could manually change a blank cell to “yes” or “no.”   
Request from the CA Area 2, Area Resource Soil Scientist

**Comment by dylan-harwell-usda** [comment]
Hi @gregb-nrcs, The 026 form does not default the Sodbust value to "No". It actually reads this value from the Field Determination layer. The Field Determination layer gets this value from the Site Prepare CLU layer (which does default Sodbust to "No"), and as part of the workflow prior to running the HEL Determination, the user is supposed to edit this layer to update any field Sobust values to "Yes" as necessary. If you are changing these values in the Site Prepare CLU layer, and they are not coming through to your 026 form, please let us know as that is a problem. But I just tested an example below, and appears to be working as expected:

![Sodbust1](https://github.com/USDA-NRCS/HEL-Tools/assets/120053864/e6b58dee-df91-4397-8538-2a3bf3bd3e31)

![Sodbust2](https://github.com/USDA-NRCS/HEL-Tools/assets/120053864/75046fe6-61e3-4158-b48f-3224c72aa41a)
