### ISSUE TITLE
Field Determination Layer does not change in the map in a continuous APRX workflow

### ISSUE THREAD

**Issue by CEM-NRCS** [USDA-NRCS/HEL-Tools#45]
When working in a single APRX and completing consecutive sites, the Field Determination layer does not remove from the map and re-add. The new Field Determination layer does generate in the new project (2nd tract/site) HEL geodatabase, but it doesn't add to the map. Instead, the Field Determination from the previous project (1st tract/site) stays in the map and never gets replaced.

**Comment by dylan-harwell-usda** [comment]
Identified the cause. The way the script is adding layers to the map, it's checking against the layer name, if the layer exist in the list of layers in the map, it does not add. Will resolve this by first checking and removing these layers at the start of the run.
