### ISSUE TITLE
Extract CLU failing for certain tracts

### ISSUE THREAD

**Issue by dylan-harwell-usda** [USDA-NRCS/HEL-Tools#48]
Issue first reported by: @jessegray2

Create Project tool is failing in the extract_CLU_by_tract script for some tracts, but not all. I was able to reproduce the error for Tracts in Georgia, as well as Colorado during my testing. Tracts in Indiana worked successfully.

![MicrosoftTeams-image](https://github.com/USDA-NRCS/HEL-Tools/assets/120053864/657f7b9c-6cb9-437b-a183-90c8fca920df)

**Comment by hgrybas** [comment]
I believe I tracked the problem down to changes in the CLU service's field and have submitted a support ticket to GEO with details.

**Comment by dylan-harwell-usda** [comment]
@hgrybas Thank you for the update! I was theorizing it might have something to do with the CLU data...

**Comment by dylan-harwell-usda** [comment]
CLU service reported to be updated and extract_CLU_by_tract functionality restored.
